### ISSUE TITLE
点开bat报不是可运行的程序

### ISSUE THREAD

**Issue by sankuka** [6DDUU6/ESurfingDialer-onekey#1]
![屏幕截图 2024-03-28 232719](https://github.com/6DDUU6/ESurfingDialer-onekey/assets/30693953/f397c888-af63-4678-859d-e76c41697cd5)
但直接跑jar是没问题的
![屏幕截图 2024-03-28 234439](https://github.com/6DDUU6/ESurfingDialer-onekey/assets/30693953/ad97822f-dcb6-4803-94ff-c4d6e7204e7c)

**Comment by 6DDUU6** [comment]
下载蓝奏云那个压缩包试试？

**Comment by sankuka** [comment]
蓝奏云那个可以😂怎么会这样呢，大佬你怎么猜到的
